# Generated by Django 2.1.7 on 2019-03-11 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('owner', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Apartment', 'Apartment'), ('Estate', 'Estate')], max_length=255)),
                ('image', models.URLField()),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
